"""typo employee

Revision ID: 9b0db3156be4
Revises: cf2f8fd3ed31
Create Date: 2025-06-18 03:24:29.560855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b0db3156be4'
down_revision = 'cf2f8fd3ed31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reviews', 'empolyee_id', new_column_name='employee_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reviews', 'employee_id', new_column_name='empolyee_id')
    # ### end Alembic commands ###
