"""add foreign key to Review

Revision ID: cf2f8fd3ed31
Revises: 5f63fec6dd75
Create Date: 2025-06-18 03:06:27.123791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf2f8fd3ed31'
down_revision = '5f63fec6dd75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('employee_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'employee_id')
    # ### end Alembic commands ###
